### ISSUE TITLE
漢字と読みをデータベース化する

### ISSUE THREAD

**Issue by fuuj** [fuuj/kanji-app#14]
[常用漢字表](https://github.com/cjkvi/cjkvi-tables/blob/master/joyo2010.txt)
[csvからSqliteテーブルへのインポート](https://qiita.com/j-shimo/items/83febe1992321ba558e4)
...
愛,アイ
曖,アイ
悪,アク
悪,オ
悪,わる-い
惡,アク
惡,オ
惡,わる-い
...
こんな感じのテーブルになればいいはず.

**Comment by knaoto** [comment]
完成しました
